### ISSUE TITLE
last stable version in presskit outdated

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/website#102]
In the presscit section on the website its written that 0.11.5 is the last stable version.
However it will soon be 0.14.2:

![bildschirmfoto vom 2018-10-19 15-48-01](https://user-images.githubusercontent.com/1891273/47222247-7f6a9480-d3b6-11e8-98b9-596e9d8b0a35.png)

**Comment by TheAssassin** [comment]
Cannot reproduce:
```
Current stable version: 0.14.1
```

You disabled JavaScript it seems, as that is the fallback value (as in, if JavaScript doesn't work, that value is left unmodified).

Check out https://github.com/TeamNewPipe/website/blob/master/press/index.html#L19.

**Comment by TheAssassin** [comment]
@TobiGr what about renaming these "defaults" to "please enable JavaScript to ..."?
