### ISSUE TITLE
add Link to documentatoin

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/website#104]
The [documentation](https://teamnewpipe.github.io/documentation/7) is not perfect, but better then nothing.
I would like to add a link to it onto the website. Right besides the the `FAQ (beta)` link. The link for the moment should be called `Documentation (Alpha)`.

**Comment by TobiGr** [comment]
Why do you want to add an (Alpha) badge? Why do not call it beta as well?
I get the point that the docs are far from being perfect and complete but I wouldn't make a difference between beta and alpha. Alpha and beta might confuse users which see the link and prevent them from clicking on it.

**Comment by theScrabi** [comment]
I see, then lets write beta on it.
