### ISSUE TITLE
Playlists shown on channels

### ISSUE THREAD

**Issue by ArtfulAbyss** [TeamNewPipe/website#113]
I have a lot of playlists that I like that don't come up on the search engine no matter what I try looking up. I suggest that being able to see the playlists that a user has made on their channel. It would make searching for playlists much easier. Thank you! <3

**Comment by TheAssassin** [comment]
This should probably go into the main NewPipe repository, shouldn't it, @ArtfulAbyss? I can transfer the issue if that's the case.

**Comment by TobiGr** [comment]
Yep, this should be moved to the app repository. But it's a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1030
Therefore I'll close this ticket.

**Comment by TheAssassin** [comment]
Thanks for confirming. Let's still transfer this one so it's in the right spot.
