### ISSUE TITLE
Apply new blog theme to "announcements" on the press page

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#118]
See https://newpipe.schabi.org/press/announcements/. Still using the old style. The new style should be used there, too, as it's much nicer.

Also, we should make sure all announcement posts really carry the right tag, I miss a few posts on that page.

We might also just drop the page and link to the Blog.

**Comment by TobiGr** [comment]
I prefer to remove the page.
Which posts would you like to label as announcement?

**Comment by TheAssassin** [comment]
If we remove it anyway, then that's not an issue any more really.

**Comment by TobiGr** [comment]
Good. I'll take care of it 👍

**Comment by TheAssassin** [comment]
Thanks. Pushed the "deploy-our-website-asap" button.
