### ISSUE TITLE
Replace F-Droid badges with vector graphics

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#12]
As mentioned in #11, we should replace the PNG graphics with vector graphics. The F-Droid project publish their artwork in a [repository on GitLab](https://gitlab.com/fdroid/artwork). The "Get it on F-Droid" badges are in [this directory](https://gitlab.com/fdroid/artwork/tree/master/badge).

I'd suggest using [this one](https://gitlab.com/fdroid/artwork/blob/master/badge/get-it-on.svg), it's the same one that is in use at the moment. As the files in the repository are Inkscape SVGs, someone has to export them to normal SVG using inkscape first. The fonts have to be embedded, too.

**Comment by TobiGr** [comment]
Internet Explorer 11 and lower only partially supports the scaling of SVG images. This causes strange picture details.
Should I find a JS workaround or ignore the few people using IE?

**Comment by TheAssassin** [comment]
Internet Explorer's market share is really low, especially in the world of free software. I don't really care about Microsoft's crap browser being unable to implement internet standards.
