### ISSUE TITLE
Grammar Suggestions [English]

### ISSUE THREAD

**Issue by RockyJE** [TeamNewPipe/website#120]
[ORIGINAL] Do you like watching videos on YouTube
but looking for a simple app to do that?

[SUGGESTED] Do you like watching videos on YouTube
but **are** looking for a simple app to do that?
..........
[ORIGINAL] Your donation cover a majority our costs

[SUGGESTED] Your donation**s** cover a majority **of** our costs
..........
[ORIGINAL] We would like to offer you some ways you can support our work by donations. So we can get some extra snacks during work!

[SUGGESTED] We ~~would like to~~offer you ~~some~~ ways ~~you can~~to support our work by donations~~So~~—so we can get some extra snacks during work!

**Comment by TheAssassin** [comment]
Looks good. Mind to send a PR?

**Comment by RockyJE** [comment]
What is a PR?

rje

Sat Jun 08 15:27:54 PDT 2019 TheAssassin <notifications@github.com>:

**Comment by TheAssassin** [comment]
https://help.github.com/en/articles/about-pull-requests
