### ISSUE TITLE
CORS header issue

### ISSUE THREAD

**Issue by Poolitzer** [TeamNewPipe/website#129]
As discussed in [this](https://github.com/TeamNewPipe/website/pull/128#discussion_r362230881) comment, local clones of the website doesn't allow "reading the remote resource at https://newpipe.schabi.org/api/data.json?json".

This is the linked mozilla developer article: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSAllowOriginNotMatchingOrigin?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

Full error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://newpipe.schabi.org/api/data.json?json. (Reason: CORS header “Access-Control-Allow-Origin” does not match “newpipe.schabi.org”).`

**Comment by Poolitzer** [comment]
Uhm @TheAssassin why did you close that?

**Comment by TheAssassin** [comment]
The issue has been resolved by changing a header in the API code and redeploying the API service.

**Comment by Poolitzer** [comment]
Oh neat
