### ISSUE TITLE
add info about auroradroid

### ISSUE THREAD

**Issue by KonoromiHimaries** [TeamNewPipe/website#138]
https://gitlab.com/AuroraOSS/auroradroid#readme

**Comment by Poolitzer** [comment]
But, uhm. Why? Isnt it another app for the F-Droid backend? And unofficial?

**Comment by KonoromiHimaries** [comment]
@Poolitzer better design

**Comment by Poolitzer** [comment]
Sure. But even if you can fight unicorns with it (which is very important, believe me), it is an unofficial app for something we already mention the official app/system for.

Imagine we add your app. Will take us probably one long or two shorter sentences, explaining the circumstances, but we get it done. Then suddenly, there are two more unofficial apps, and they want also to be mentioned here. So, we have a dilemma: Do we add them and anything else which comes up (unofficial, like apkmirror. An aurora mirror (iirc thats also an app store). Another apk website). Or do we stop after your suggestion. Then we have to explain to others why, and our arguments would be bad.


What I am trying to say: Your suggestion has a potential long tail which defeats the idea of this little section. Its just there to quickly inform users where to get it from. I dont see a reason to start mentioning any more unofficial pages/apps there.

**Comment by KonoromiHimaries** [comment]
> Sure. But even if you can fight unicorns with it (which is very important, believe me), it is an unofficial app for something we already mention the official app/system for

> Imagine we add your app. Will take us probably one long or two shorter sentences, explaining the circumstances, but we get it done. Then suddenly, there are two more unofficial apps, and they want also to be mentioned here. So, we have a dilemma: Do we add them and anything else which comes up (unofficial, like apkmirror. An aurora mirror (iirc thats also an app store). Another apk website). Or do we stop after your suggestion. Then we have to explain to others why, and our arguments would be bad.

remove f-droid, to not generate ecology cost. google play is one one one best solution ever. nothing, NewPipe is unofficial app and banned in gp : )

make sure, do not support software that offers greater benefits!

**Comment by Poolitzer** [comment]
you didn't get my point. If we add more apps to that list, where does it stop?

**Comment by KonoromiHimaries** [comment]
@Poolitzer in new repo, like https://github.com/sindresorhus/awesome

**Comment by TobiGr** [comment]
users of auroradroid, G-Droid and other F-Droid clients know what their client does and where the apps come from: the F-Droid repository. Thus it is enough to say that NewPipe is available through the main F-Droid repository.
Apart from that, @Poolitzer is right. When we start to list one additional client, we need to mention all. So better list no one.
