### ISSUE TITLE
0.58.5 instead of 0.18.5

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/website#141]
The name of https://github.com/TeamNewPipe/website/blob/master/_posts/2020-02-26-newpipe-0.58.5-released.md has 0.58.5 in it instead of 0.18.5 like it should be. @B0pol noticed that on IRC.

**Comment by B0pol** [comment]
![](https://i.kym-cdn.com/entries/icons/original/000/029/790/2gi1lylqezh21.jpg)

**Comment by TheAssassin** [comment]
See also https://github.com/TeamNewPipe/website/pull/140#issuecomment-591808480.

**Comment by TheAssassin** [comment]
Fixed in #140.
