### ISSUE TITLE
FAQ: why is this not on Google Play

### ISSUE THREAD

**Issue by tbm** [TeamNewPipe/website#153]
The repo clearly states:

> PUTTING NEWPIPE OR ANY FORK OF IT INTO GOOGLE PLAYSTORE VIOLATES THEIR TERMS OF CONDITIONS.

But I can't find why.  I guess it's because you're not using their API or something, but it would be nice to have that explained somewhere for those who are wondering.

**Comment by B0pol** [comment]
It's violating YouTube ToS (see the right and restrictions, scrappers are mentionned as forbidden). Maybe it's the reason why, I haven't read Google Play ToS.

**Comment by tbm** [comment]
Oh, that makes sense.  So maybe it's better not to document it too widely.

**Comment by TheAssassin** [comment]
We are not lawyers and don't give legal advice. However we have come to the conclusion that a violation with any sorts of Google terms is likely.

Personally, I see no reason to pay _them_ money to distribute a privacy-respecting app in their surveillance-based tracking environment. That's one huge misconception. You pay them money and then are at risk of them to deal with your app(s) arbitrarily and randomly without any control and an ineffective complaint system?

I think we can close the issue at this point.

@tbm for more informal questions, you can also join our IRC channel.
