### ISSUE TITLE
Linebreak on frontpage seems strange

### ISSUE THREAD

**Issue by tbm** [TeamNewPipe/website#155]
There's a linebreak on the frontpage:

```
index.html:                        <p><strong>Do you like watching videos on YouTube<br>but want an intuitive, feature-rich and privacy friendly app for that?</strong></p>
```

I don't see a particularly good reason to break this sentence there.

**Comment by tbm** [comment]
I just noticed:

> The lightweight
> YouTube experience
> for Android

I think splitting that makes more sense than the other sentence I pointed out, but even here I'm not sure.  If it was placed a little bit further below, it could easily fit into one line.  But feel free to disagree.

**Comment by TheAssassin** [comment]
Please feel free to send a PR.
