### ISSUE TITLE
Make NewPipe logo go back to home page

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/website#162]
Why does it come back to category page? I've never seen a website doing this, they all go back to main page when I click on the logo.

**Comment by TheAssassin** [comment]
Where exactly do you experience this behavior?

**Comment by B0pol** [comment]
FAQ, blog, press

**Comment by TheAssassin** [comment]
I only know that in the blog, this occurs, but you're right, it should just redirect to the index page. CC @TobiGr
