### ISSUE TITLE
"Advertise" RSS / ATOM

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/website#164]
I've seen we have RSS and ATOM feeds by looking at the source code. We really should have an icon which links the feed in the blog section
<img src="https://upload.wikimedia.org/wikipedia/en/4/43/Feed-icon.svg">

(and the icon should be red themed like newpipe btw)

**Comment by TobiGr** [comment]
We link the feed in the sidebar. If you want, I can increase the font size.
![Screenshot_2020-06-20 NewPipe - a free YouTube client](https://user-images.githubusercontent.com/17365767/85208916-42e1ff80-b334-11ea-82f5-6ad5d7757577.png)

**Comment by TheAssassin** [comment]
It's pretty invisible there. Maybe move it or change the color?

@B0pol you can also just enter https://newpipe.schabi.org in your RSS reader, we link the Atom/RSS feed in the HTML sourcecode, too.

**Comment by B0pol** [comment]
Uh, it's just ublock origin Fanboy's annoyance list removing rss icons (or even some links). I didn't know that, sorry
