### ISSUE TITLE
Link to import/export tutorial 404s

### ISSUE THREAD

**Issue by gkeegan** [TeamNewPipe/website#167]
On this page: https://newpipe.schabi.org/FAQ/
if you expand the "Upgrading NewPipe fails", and click the link that says "this tutorial" you are taken to 404 page.

**Comment by TobiGr** [comment]
cannot reproduce anymore. Can you?

**Comment by gkeegan** [comment]
It still happens for me. I get the generic nginx 404 page.

**Comment by Poolitzer** [comment]
no he is right simple fix hang on
