### ISSUE TITLE
Would u add a close button in a popup widow?

### ISSUE THREAD

**Issue by donlet** [TeamNewPipe/website#174]
Hi~

I'm so glad to know Newpipe app.
The app quenches my thirsty.
I suggest a close button in popup window even though the window drags the bottom area to close.
And also it's better to close a popup window to replay when I tap the popup button of same video again.

I look forward hearing from you soon.
Thank you.

**Comment by Poolitzer** [comment]
Hey, you mean a closer button in the app? Because you just created an issue in the repo for the website...
