### ISSUE TITLE
News or blog

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/website#20]
An interesting page of the new website could be a blog or news section where the developer announce new features and versions of NewPipe or other interesting things like articles about NewPipe in the media, statistics and information about upcoming events.
To be honest, it isn't useful at the moment, but at a later point in time it could be helpful. 
@theScrabi @TheAssassin  @ponypower Tell me what you think about it.

**Comment by theScrabi** [comment]
TheAssasine and I had a conversation about this already. He urged me months ago that I should start a blog about NewPipe.

**Comment by theScrabi** [comment]
But I think for now we should focus on finishing the website as it is, and later talk about a blog etc. What do you think?

**Comment by TobiGr** [comment]
Yes I totally agree with you. 
I asked that question because we now can discuss whether we should always show the latest article on the main page or only provide a link to the blog in the navigation or/and the footer.

**Comment by theScrabi** [comment]
It might be more catchy if the latest article is shown.

**Comment by TobiGr** [comment]
@ponypower We can add a news section add the bottom of the page including the latest article and a download link for the CCC presentation. What do you think?

**Comment by ponypower** [comment]
@TobiGr Sure. I find this too a good idea. Do you need any support design wise?
As far as I remember the CCC presentation contains only a limited amount of information. Dunno if that interests many people. I think completing it with additional notes (what was mentioned at the presentation) would be nice.

**Comment by TobiGr** [comment]
@ponypower You are right. The presentation isn't enough to inform the user about how NewPipe works. My idea is that this can be done in some blog entries which are pinned on the right side of the blog page. I'm thinking of something like this:
![blog-1](https://cloud.githubusercontent.com/assets/17365767/25970756/0039fe4a-369a-11e7-8272-39c8233cd920.png)
>As far as I remember the CCC presentation contains only a limited amount of information. Dunno if that interests many people. 

I'm - as user - not interested to click through a presentation to get only few useful information. Do you agree on removing the embedded presentation from the main page (it's displayed differently by every single browser too) and replacing it with a link to it?

@theScrabi @TheAssassin Btw. I don't think that this blog is going to be that big, but working with a database will be necessary and make the handling of the data more easy.

**Comment by ponypower** [comment]
> ... removing the embedded presentation from the main page ...

No reason to embed the presentation. A download link is just enough.

**Comment by TobiGr** [comment]
This is my first design for a single article page.
I'm struggling with the (optional) comments right now. @theScrabi @TheAssassin  Do you think we'll need them?
Tell me what I can improve.

Design without comments:

![blog-10](https://cloud.githubusercontent.com/assets/17365767/26577496/daaa3842-452c-11e7-9da6-8c64689674a9.png)

Design with comments:

![blog-9](https://cloud.githubusercontent.com/assets/17365767/26577522/e997cc7a-452c-11e7-929e-183d8b891efe.png)

**Comment by TobiGr** [comment]
@TheAssassin I think a CMS for the blog is quite useful and saves a lot of time I'll spend on development. I suggest to use either Wordpress or Typo3. What do you think?

@ponypower This is how the latest article can look like on our main page.
![screenshot 20 - full - blog - 2](https://cloud.githubusercontent.com/assets/17365767/26686632/daa635b8-46ed-11e7-943d-613a4579b4cf.png)

**Comment by TheAssassin** [comment]
Wordpress is itself a security hole, and Typo3 is full of issues, slow, bloaty and overall sucks.

If you want a blog, please check out static publishing systems, like Jekyll or Pelican. They are secure, fast, can be stored in git. Simply put, perfect. With some JavaScript magic, we can display the latest article easily on the site.

**Comment by TobiGr** [comment]
Yeah, you're right. Wordpress and Typo3 would need a lot of maintenance time later on. So Jekyll seems to be a good solution to me. But before I will focus on the development of the blog, the main page should be finished.

**Comment by TheAssassin** [comment]
Yep, that's what I would suggest, too.

**Comment by TobiGr** [comment]
I've played a little with some designs and ended up with [this](https://github.com/TobiGr/NewPipe-Blog) as my first idea of the blog. It's just a first try, so things like many links, the sidebar and the mobile version don't work as expected and they have probably some issues. But before I'm going to spend more time on it, I need feedback of what you think of it.

**Comment by TobiGr** [comment]
@TheAssassin @theScrabi I have been working on the development of the blog this week. I think that it still needs a few smaller design improvements, but apart from that only the content is missing. Before posts get written we should open a new repository for the blog. 

If we want to use comments the whole thing is going to be more complicated. There are several ways to make comments possible:

Use PHP and database:
- [lumen](https://lumen.laravel.com/): a framework which provides all functions and is fast. Problem: not static at all. [Here](http://savaslabs.com/2016/04/20/squabble-comments.html) is an interesting article on this topic.


Use PHP scripts on our servers:
- [ jekyll-static-comments](https://github.com/mpalmer/jekyll-static-comments): a plugin for Jekyll 2 which needs only PHP to send us the comments via mail. It works like this: 
Someone writes a comment, hits the submit button, the form calls a PHP script which sends you all the needed information on this comment (post id, title, comment, email address of the guy who commented (optional but good for questions / if something is unclear). Then you have to add a Markdown or HTML file with the YAML frontmatter and all information from the email to the blog. Adding the comments manually to the repository is a disadvantage because you can only add comments to blog when you have a device with any kind of Git application with you. So a team of people who cares about comments is needed if you want to publish comments without a too big delay. Another disadvantage is that the plugin is not under active development and not compatible with Jekyll 3. Possible solutions which I haven't tested yet: [mpalmer/jekyll-static-comments#20](https://github.com/mpalmer/jekyll-static-comments/issues/20)
Advantage: Full control of which comments are published. No spam, no offensive comments.

Do not use any PHP scripts or databases on our servers:
- [Disqus](http://disqus.com): the most common way. This would mean, that all comments were stored at Disqus servers and we only needed to call a JS script to load the comments. I'm not sure if this is a good idea, precisely because Disqus is well know for tracking the users browser history.
- Google and Facebook comments: same problems and you need an account
- [GitHub comments](ivanzuzak.info/2011/02/18/github-hosted-comments-for-github-hosted-blogs.html): For every article you have to open an issue where people can comment. Uses GitHub API to get the comments. Limited to people who have an GitHub account.

Use no scripts and no external servers:
- jekyll-static-comments plugin without the PHP script: As the PHP script's only function is to send the mail, we can use JavaScript to modify a HTML link to do so. The user writes his comment in the browser and when he clicks the submit button the default email application gets opened and the user needs to send the email by clicking on the send button. This is quite inconvenient for the user but keeps our blog static. 

The last one seems to be the best. But before I dig any deeper into this, we should determine if we will need support for comments on articles.

**Comment by TheAssassin** [comment]
Well, I'd rather keep this repository as static as possible. I'm not even sure whether comments are that useful, but if you really want to implement them, I'd go for the Disqus approach. There is a self-hostable alternative for Disqus: https://posativ.org/isso/

I've tried it a while ago, and it worked fine. Might be worth to try that first of all. I'd set up a demo if @theScrabi and the others think that comments would be useful (I still don't).

**Comment by TobiGr** [comment]
@TheAssassin I am also not sure if we will need comments. That's why I asked. But if you want to keep it static (I'd prefer that too) we can test the jekyll-static-comments plugin. It seems to be more static but needs maintenance.

**Comment by TheAssassin** [comment]
The only thing static about that plugin though is that it uses flat files. I'd rather host an external system for comments though, like isso, because that's fully separated and might come in handy for some other of my projects.

**Comment by TobiGr** [comment]
The blog is ready to use. I couldn't decide which design is better, so please take a look at the [master](https://github.com/TobiGr/NewPipe-Blog/tree/master) and [design](https://github.com/TobiGr/NewPipe-Blog/tree/design) branches and tell me what you like more.
The links on the right sidebar have no function right now, but will refer to any interesting posts once they are written.
And please create a new repo for the blog.

**Comment by theScrabi** [comment]
I created the [repo](https://github.com/TeamNewPipe/BlogGenerator). @TobiGr you are admin.

**Comment by TobiGr** [comment]
Thanks. I'll take care of the rest.

**Comment by theScrabi** [comment]
thanks

**Comment by TobiGr** [comment]
> I am in favor of the latter.

Me too. But please wait with that until the demo posts and links got removed and @theScrabi or someone else wrote a initial blog post.

**Comment by TheAssassin** [comment]
Just write me a mail (and really, a mail, because I'm flooded with GitHub notifications atm), and I'll deploy stuff as you wish.

**Comment by theScrabi** [comment]
Ok I'll write something.

**Comment by TobiGr** [comment]
@theScrabi I've finshed my work on the blog. So we only need the initial blog post. And maybe we should disable the c33 post.

**Comment by TheAssassin** [comment]
@theScrabi I recommend you to hurry up, too. If you want to, we can collaborate on a post. @TobiGr otherwise I'd write up something.

**Comment by TheAssassin** [comment]
@TobiGr I am in the progress of setting up a comment system by the way. It's called [isso](https://posativ.org/isso/). Can you check whether how we can integrate it easily?

**Comment by TobiGr** [comment]
@TheAssassin Yes, I got it running. I will do some testing whether I can restructure the comment output, to apply our design to the comments.

**Comment by theScrabi** [comment]
@TobiGr @TheAssassin I red through the two posts in the pad, and I think they are good now.

**Comment by TheAssassin** [comment]
@TobiGr I committed a Docker configuration for easy deployment. I will add the isso configuration to the docker-compose file eventually.

**Comment by TheAssassin** [comment]
The look of the single blog posts is a bit too bright in my opinion, especially during mouse-over events. Could you make it look a bit more native? The rectangular shape with the really hard contrasts doesn't really match the rest of the website.

Also, I'd recommend to display the "Blog" entry in the top menu bar as "selected" when visiting the blog.

By the way, I hope you don't mind me editing your blog post. I want to reword it a bit, and fix a few facts.

**Comment by TheAssassin** [comment]
Somehow it seems like not all of the blog posts are rendered. I'll be investigating that tomorrow. I could imagine a multi-page layout, displaying most posts in the sidebar for quick access.

**Comment by TobiGr** [comment]
> Somehow it seems like not all of the blog posts are rendered. I'll be investigating that tomorrow. I could imagine a multi-page layout, displaying most posts in the sidebar for quick access.

@TheAssassin I can take a look at it too. I guess the dates of your posts weren't correct. I do not display posts which have not been "released" and were written in the "future".

**Comment by TobiGr** [comment]
@TheAssassin I've checked and all posts are displayed. I saw you removed the pinned posts from the sidebar. The search input looks lonely now. We should add some links or text to it. Maybe we can pin the "Team NewPipe start blog" post.

**Comment by TobiGr** [comment]
> The look of the single blog posts is a bit too bright in my opinion, especially during mouse-over events. 

I took the two shades of grey which we also use at our main page. I can understand that they distinguish from each other a lot. 
What do you think of [this](https://user-images.githubusercontent.com/17365767/34107404-6279eb6e-e3fc-11e7-8feb-40f91b688016.png)? I mixed both colors and changed the border color to white. The first post has the hover effect.

> Also, I'd recommend to display the "Blog" entry in the top menu bar as "selected" when visiting the blog.

I'll do it.

> I think we should "generate" that somehow, e.g., introduce a category "pinned", and render all these posts in the sidebar, unless there is a standard pinning process.

That's a good idea.

**Comment by TheAssassin** [comment]
The shadow looks a bit awkward.

**Comment by TobiGr** [comment]
I'll remove it.

**Comment by TobiGr** [comment]
@TheAssassin Comments will look like[ this](https://user-images.githubusercontent.com/17365767/34122518-fe75b608-e42c-11e7-8ef8-9bccfa496222.png). Are you fine with it?

**Comment by TheAssassin** [comment]
Looks great!

**Comment by TobiGr** [comment]
@TheAssassin I didn't add `isso.config`, that's something you have to do.

**Comment by TheAssassin** [comment]
As said before, the deployment will be done via Docker. I am going to use https://hub.docker.com/r/sheogorath/isso-docker/, which is configured via `docker-compose.yml`. Don't worry, I'll set up everything correctly, once we're ready for deployment.

**Comment by TheAssassin** [comment]
I will close the issue when everything is deployed.
