### ISSUE TITLE
get webstorm license

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/website#21]
@TobiGr 
The Project of the website is now more than 3 months old. Isn't it now pissible for you to get a webstorm licinse?
https://www.jetbrains.com/buy/opensource/?product=webstorm#application-rules

**Comment by TobiGr** [comment]
> Your OS project meets the [Open Source definition.](http://opensource.org/docs/osd)

Before I can get it, we will need a license, which @TheAssassin wanted to create.

> You release updated builds on a regular basis.

At the moment there are no published 'builds' for the website. If I understand that correctly, we have to publish at least some early state of the website to any domain.

Btw. I have a license for IDEA and PhpStorm, so I can get one for webstorm easily too.

**Comment by wb9688** [comment]
Why'd you even want to have WebStorm?

**Comment by TobiGr** [comment]
Good question

**Comment by TheAssassin** [comment]
Closing as this is not an issue with the website repository but about the tools of single developers and thus pure offtopic.

**Comment by TobiGr** [comment]
@theScrabi We can discuss this at the irc channel

**Comment by theScrabi** [comment]
We could yea. I dont need webstorm, I get the license from my university. I yust eated to remind xD you, if someone was interested xD.
