### ISSUE TITLE
overflow on mobile

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/website#210]
https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

**Comment by Poolitzer** [comment]
That page looks fine on my end what do you mean exactly with overflow?

**Comment by B0pol** [comment]
I mean that:

<img src="https://user-images.githubusercontent.com/58657617/103111336-3d9b9f80-464c-11eb-8969-c90712b4f898.png" width="300"> <img src="https://user-images.githubusercontent.com/58657617/103111337-412f2680-464c-11eb-8749-34c8cc94e862.png" width="300">

It's not fixed @TobiGr , please reopen

**Comment by TobiGr** [comment]
I forgot one `<code>` tag, but for some reason, the problem is not solved yet. Will dig into that one another day.

**Comment by TobiGr** [comment]
Overflow is caused by https://github.com/TeamNewPipe/website/blob/846ed4416fa218722da1c80097d6a89a6977393c/css/faq.css#L344-L350. Don't ask me what I did there and why I did that. Will take a look at it tomorrow.
