### ISSUE TITLE
Figure out licensing

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#23]
Continuation of the discussion in #18.

We have to figure out how to properly use external resources.

Questions to be answered:

* Do we have to mention what frameworks and libraries we use?
* If yes, how?
* How can we license the contents in this repository?
  * Pick separate licenses for code and content?

This is probably the last step to be done before going live with this site.

**Comment by TheAssassin** [comment]
@TobiGr I understood your statement about licensing everything as CC-0 that you were okay with the licensing I just published (MIT for code, CC-BY-SA 3.0 for contents). Can you please verify that this is okay for you?

**Comment by TobiGr** [comment]
@TheAssassin Yes, that looks good to me.

_Sent from my Motorola MotoE2(4G-LTE) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TheAssassin** [comment]
Thanks. Deployment is on its way.
