### ISSUE TITLE
Add link to really basic documentation

### ISSUE THREAD

**Issue by jidanni** [TeamNewPipe/website#243]
On https://teamnewpipe.github.io/documentation/
  add a link for users who just want to find out how to watch a couple movies.

**Comment by jidanni** [comment]
One example is so-called gestures that we see in the settings mentioned. Well I certainly couldn't figure out how to find those gestures so I can't tell if they're working or not. So the best I could do is just turn off the setting.

**Comment by jidanni** [comment]
Also, all the documentation should also be available within the app itself too. Because you never know when somebody might be offline.

**Comment by Poolitzer** [comment]
> Also, all the documentation should also be available within the app itself too. Because you never know when somebody might be offline.

I think that would be pretty hard to implement UI wise, not to mention one would need to translate them? anyway, you would need to open a new issue for that :D

**Comment by TobiGr** [comment]
https://teamnewpipe.github.io/documentation/ is a documentation for devs. Not for users. And information on how to use the app should be given inside the app. 

However, we have a (outdated) FAQ here: https://newpipe.net/FAQ
