### ISSUE TITLE
[SOLVED] Background Music Player / Control Missing 

### ISSUE THREAD

**Issue by machantoshi** [TeamNewPipe/website#288]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.

#### What's your question(s)?
Hi, I'm new here. Just wondering about Newpipe background player.
I've tried searching about this issue but could not find it, or maybe I didnt search the right term (if so, sorry).

Since several updates ago (or maybe since I updated to Android 11, I no longer see the Background Player function.
Used to be able to do everything perfectly (play, pause, shuffle, repeat, etc) from notification or in-app background player.
Now all background player / music only are gone (can only play the one song I pick and it will stop after finished; or use auto-play to randomly play whatever is the next song).

Is this ongoing issue with Android 11 or am I missing something?
Thank you for your help.

#### Additional context
Phone: Poco F3
OS: MIUI Global 12.5.2 Stable
Android: 11 RKQ1.200826.002

Issue steps:
- When "Background" is clicked, music will play, but remains in normal video page
- Music player isnt available anywhere
- When minimized, notification player also not available
- All required settings allowed

What I've tried:
- Clear data / cache
- Clean install app (Tried this several versions) 
- Restart phone

**Comment by Mohamed6g** [comment]
I own an Oppo A52 phone, Android version 11. Well, the problem started when I force-stopped the Google Play Services application. I only find 360 quality for all videos, and when I download a video, I only find 360 quality. Is there a solution? I mean, I really deleted your application and downloaded it again, but it did not work. I also deleted its data, but it did not work. I deleted the Google Play Services application updates and updated them again, but it also did not work. Are there any solutions? 

![Image](https://github.com/user-attachments/assets/faedfdf4-1879-4132-997b-7e2957edf4e8)

![Image](https://github.com/user-attachments/assets/28694f9a-6500-4f6f-b42b-20e60bab29d9)

![Image](https://github.com/user-attachments/assets/127337db-7951-4c27-addb-72be26c6d426)

![Image](https://github.com/user-attachments/assets/4d67abae-aeb8-4bc3-8aad-baf1a4ea4e36)

![Image](https://github.com/user-attachments/assets/2a814168-0591-4cb4-92fd-eb6c00988d3d)
