### ISSUE TITLE
Adding newpipe.net repo to F-Droid results in an error

### ISSUE THREAD

**Issue by UmBottesWillen** [TeamNewPipe/website#294]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Follow steps detailed in the [tutorial](https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/) on how to add the custom newpipe repo to F-Droid.
2. Update the sources list of F-Droid by swiping downwards in the Tasks view.

### Expected behavior

The sources list is updated successfully.

### Actual behavior

The update fails with the message: "archive.newpipe.net/fdroid/repo: Error getting F-Droid index file => null"

### Affected Android/Custom ROM version

Android 11

### Affected device model

Fairphone 4

### Additional information

This bug seems to be experienced by multiple people, if this [reddit thread](https://www.reddit.com/r/NewPipe/comments/wp1ebh/adding_the_newpipenet_repo_to_fdroid_results_in/) is to be believed.

**Comment by LinoMastro** [comment]
I'm also affected by this and for me removing and adding back the repository doesn't fix the issue (I've tried several times).

Every time I add the repository (or simply disable it in F-Droid and enable it again) I get the error message mentioned in the first comment.

This happens only with the NewPipe repository, I tried adding custom repos from other projects and they load correctly.

I'm using the current stable F-Droid client app, version 1.15.2.

**Comment by EvanCarroll** [comment]
This solution worked for me

https://android.stackexchange.com/a/248048/7425

**Comment by xyoutuber** [comment]
I'm really not tech savvy so not sure what I'm doing. I clicked on download Fdroid on the link you sent me and got message "not installed as pkg. so won't work" or something like that.
I appreciate your trying to help me. Do you have any other ideas how to download a WORKING Fdroid app?
Thanks, Linda Balzan
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Aug 16, 2022, 6:41 PM by ***@***.***:

**Comment by EvanCarroll** [comment]
Not sure at all what error you're getting there. The easy way to download the NewPipe App is to just remove all copies if you have any of the NewPipe App and download the newest APK here,

* https://github.com/TeamNewPipe/NewPipe/releases

The problem with that is you have to manually upgrade. To make that easier you can install F-Droid. Then you have automatic upgrades. The problem here is that the latest version of F-Droid doesn't work with any previously installed NewPipe Apps, on the NewPipe repository. So you have to remove any NewPipe Apps to install the NewPipe repository **FIRST**. Then everything just works.

**Comment by xyoutuber** [comment]
I really appreciate your trying to help me (an old, not tech savvy lady)!!
I got NewPipe to work again, not sure if I did it or if it just started working on its own. 
My only problem now is that the Fdroid store app that came with this degoogled phone stopped working.  Not many apps there and if I see one I want, when I click on down arrow, it just flashes, won't download. Any ideas to help me with this problem?
Will wait to hear back.
Thanks, Linda Balzan
209-712-7377
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Aug 16, 2022, 11:32 PM by ***@***.***:

**Comment by LinoMastro** [comment]
I finally figured out the problem: if you paste the full URL from the NewPipe documentation "https://archive.newpipe.net/fdroid/repo/?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501" into the "repository address" field in F-Droid, you get the "null" error message mentioned at the beginning of this bug.

What F-Droid actually wants is only the first part of the URL in the address field, i.e. only https://archive.newpipe.net/fdroid/repo/

And the hexadecimal fingerprint should be pasted only in the fingerprint field.

It's probably obvious to anyone who has done successfully before, but it wasn't obvious to me (and the others that encountered the issue) that the fingerprint must be removed from the URL, following the instructions at: https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/

Can you please update the documentation with more details on what exactly belongs in each field. The screenshot in the doc truncates the URL, so it doesn't show that the fingerprint should be cut out from the address.

**Comment by Poolitzer** [comment]
Yes, thats a sensible update indeed

**Comment by opusforlife2** [comment]
Whoops. I completely forgot to close this. Fixed by #295.
