### ISSUE TITLE
archive.newpipe.net does not support TLS secure renegotiation, causing f-droid to fail updating

### ISSUE THREAD

**Issue by hilariousperson** [TeamNewPipe/website#297]
When updating the newpipe upstream repository, F-Droid fails with the following error: `Error getting F-Droid index file => java.security.cert.CertPathValidatorException: Trust anchor for this certification path not found.`

Checking with `curl` and `openssl s_client` reveals that it seems archive.newpipe.net does not support TLS secure renegotiation, used to prevent certain Man-in-the-middle attacks. I believe this causes F-Droid, as well as OpenSSL and Firefox, to be unable to fetch anything from https://archive.newpipe.net

I don't know if this is the best place to report errors with the f-droid infrastructure but I haven't found better.

Cheers and thanks for the great software.

**Comment by opusforlife2** [comment]
Why did you close this?

**Comment by hilariousperson** [comment]
I realized this was over-eager internet filter trying to Man-in-the-Middle my connection to this specific server for some reason. This is not a problwm witj NewPipe after all.

**Comment by opusforlife2** [comment]
Thanks for confirming!

In general, it's a good habit to provide an answer for the sake of others: https://xkcd.com/979/
