### ISSUE TITLE
Verify copyright for phone animation 

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#3]
We need to find a license for the phone animation and include that into the repository as mentioned in #2. Otherwise, the use and distribution might result in a copyright infringement, which is not desirable for anyone involved.

**Comment by TheAssassin** [comment]
@theScrabi you provided the files of the current website, do you know anything about its license?

**Comment by theScrabi** [comment]
Well ... not really. I know that [drakon5](https://github.com/darkon5) created the website (at least I think it was him). He initially created a website, and we just took the files from his site and put it at your server.

**Comment by TobiGr** [comment]
Depending on the frame rate and the resolution we could use GIF-animations instead. But I am not sure how large the files will become.

**Comment by TheAssassin** [comment]
This doesn't solve the copyright questions at all. It doesn't depend what format the file has but how the author licensed it.
And actually WebM is a lot more suitable for this kind of use case than GIF (GIFs are, as you implied, bloaty, uncompressed files, WebM is a real codec for videos). They're widely supported nowadays, it's not like in 2005.

**Comment by theScrabi** [comment]
1. I think the creator would not care
2. As I said that video is obsolete, we'd have to recreate it anyway.

**Comment by TheAssassin** [comment]
@TobiGr are we still using that file? I don't think so, and think we can close this issue.

**Comment by TobiGr** [comment]
We still use it, but I wanted to create a new. Unfortunately I forgot about it. See [#13](https://github.com/TeamNewPipe/website/issues/13#issuecomment-346700775) for my last try.

**Comment by theScrabi** [comment]
We could upload your last try. It was not 100% perfect, but still better than what is online right now :)

**Comment by TheAssassin** [comment]
@theScrabi the point of this issue is the copyright problem, not the look.

**Comment by TobiGr** [comment]
I'll replace the old and create a better one when I have more time for it.

**Comment by TheAssassin** [comment]
Thanks, @TobiGr.
