### ISSUE TITLE
Canais não aparecem os vídeos 

### ISSUE THREAD

**Issue by RRobso** [TeamNewPipe/website#308]
![Screenshot_20221104-202718_NewPipe](https://user-images.githubusercontent.com/117491826/200092670-6e2df512-bedf-4970-9784-bd247a1895d2.jpg)

Todos os canais que estou inscrito e até os que não estou inscrito, não aparece os vídeos publicados

**Comment by Poolitzer** [comment]
Hey, please open your issues in english and in the correct repository
