### ISSUE TITLE
NewPipe request functionality

### ISSUE THREAD

**Issue by UseMarkus** [TeamNewPipe/website#312]
First of all: I am a complete newbee and impressed by all your commitment.

I am using NewPipe and was wondering;

- can Newpipe stop/play with the same controls as my musicplayer? I.e. the controls of my headphones.
- can NewPipe be fullscreen on my Lenovo Tab ?
Thanks for your input.
Markus

**Comment by UseMarkus** [comment]
I want to add: no fullscreen in productivity mode, so landscape with keyboard attached.
i just realised that in -normal- mode it works fine.

**Comment by UseMarkus** [comment]
Stop/play is fine now, I tested it agin and it works fine.
In productivity-mode however I cannot select fullscreen.

**Comment by opusforlife2** [comment]
Wrong repo.
