### ISSUE TITLE
Feature request: Organize playlist view

### ISSUE THREAD

**Issue by nmcsilva** [TeamNewPipe/website#317]
Hello everybody. I discovered this software (NewPipe) and I am very satisfied with its functions. However, I wanted to make a feature request. I don't know if I'm in the right place, if I'm wrong I would appreciate you explaining how to do it. The request is very simple: within the playlists created, I wanted to be able to organize the videos in order of addition, from the most recent to the oldest. And also being able to have other options like the date of the video itself. It's just that I usually like to see the videos that were recently added first, because some videos I leave to watch later and that way they end up at the bottom of the playlist. Do I make myself understood? Ex: Date of addition (most recent); Date of addition (oldest); Publication date (most recent); Date of publication (older).... Thank you for all your collaboration on this topic. Yours sincerely.

**Comment by Poolitzer** [comment]
Hi, the correct repo is https://github.com/TeamNewPipe/NewPipe, please also make sure to search if your suggestion already exists.
