### ISSUE TITLE
@TheAssassin We need to update our privacy policy when merging this. From https://sponsor.ajay.app/about/:

### ISSUE THREAD

**Issue by shaharulislam999** [TeamNewPipe/website#325]
@TheAssassin We need to update our privacy policy when merging this. From https://sponsor.ajay.app/about/:

> When you submit a sponsor, a few things are stored. The data for the sponsor, the video id, and a hashed version of your user ID is stored. Your user ID is a randomly generated UUID generated by your browser. As well as these, a hashed + salted (5000 times) version of your ip address is saved. This is to be able to rate limit one ip sending way too much spam. Why is this hashed? This just adds an extra layer of security if there is a database breach. After hashing it this many times, it becomes extremely difficult to reverse it and find what your actual IP address is, but I can still verify that the current connection is from that hashed ip. By hashing it 5000 times and salting it, brute forcing would take longer to do. 

> As well as these, whenever you submit a sponsor, it tells the server and the server records one "view" on that sponsor. No IP data or userID data is collected for this. This is to make it so that you can see how many people you have helped and I can see how much the extension is being used. However, I perfectly understand why someone wouldn't want this data logged, so there is an option to disable this if you would like.

Above is not mentioned that we transfer the id of the video the user is currently watching to their services.

[Here](https://gist.github.com/ajayyy/aa9f8ded2b573d4f73a3ffa0ef74f796) is a link to their privacy policy.

@TheAssassin I suggest to show a dialog similar to the one when submitting a crash report when enabling this feature in the settings. What do you think?

_Originally posted by @TobiGr in https://github.com/TeamNewPipe/NewPipe/pull/3205#pullrequestreview-370976694_

**Comment by TheAssassin** [comment]
NewPipe decided against Sponsorblock a long time ago. There is no need to adjust any policy. You misunderstood @TobiGr's words.

**Comment by xyoutuber** [comment]
How do I unsubscribe or can you do it for me?
Not tech savvy!!
Thanks,
Linda
