### ISSUE TITLE
SkyTube in Press Kit links to scam website

### ISSUE THREAD

**Issue by Neelfyn** [TeamNewPipe/website#332]
### Steps to repro
1. Visit https://newpipe.net/press/
2. Under _About NewPipe Extractor_, click `SkyTube` link

### Expected result
The link takes you to a webpage managed by SkyTube, such as [GitHub](https://github.com/SkyTubeTeam/SkyTube) or [F-Droid](https://f-droid.org/en/packages/free.rm.skytube.oss/).

### Actual result
The `skytube-app.com` domain appears to have been acquired by a third party and redirects to a variety of scams, such as fake virus warnings.

**Comment by TobiGr** [comment]
Will be fixed by #333
