### ISSUE TITLE
Donation button hotfix's modal interferes with moving background

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#35]
The hotfix I just merged in #34 interferes with the moving background picture showing those faces. The problem is that the picture is centered and not anchored to either side of the page.

When the modal pops up, and the scroll bar vanishes, the side width changes, and the centered background picture moves a little to the right.

I assume this would occur with any modal popping up on one of the pages. I assume #27 is affected as well. We should fix that behavior.

**Comment by TheAssassin** [comment]
Update:

I noticed that the whole page moves a bit, and that's actually mandatory, as the rest of the page is centered as well. The problem rather arises when watching the slideshow while opening up the modal. Somehow, the slideshow is not centered, but orientates at the left side of the page.

Either way, we need a fix for this. I guess the proper solution is to fix the anchor of the slideshow rather than attempting to somehow use `display: absolute/fixed` on the rest of the page.

**Comment by TobiGr** [comment]
Thank you for the invitation.
I do not have time to look at these issues until Sunday, but I'll fix them as soon as possible.

**Comment by TobiGr** [comment]
This was faster than I thought. I think we can live with not disabling the scrollbar.

**Comment by TheAssassin** [comment]
I'd call this a hack. But yes, works like a charm!
