### ISSUE TITLE
Donation page: spelling error and confusing red word/link

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/website#38]
Could somebody do s/work the/work, they/ on [this page](https://newpipe.schabi.org/donate/)? On the same page under Thank you! the word free looks exactly the same as the link GitHub, which is a little bit confusing.

**Comment by TobiGr** [comment]
@wb9688 What do you mean by _do s/work the/work, they/_? Should I only remove the highlighting of free or do you want me to do something else?

**Comment by wb9688** [comment]
It's a regular expression, which says 'work the' should be replaced with
'work, they'. See that sentence on the page and you'll see what I mean.

>Should I only remove the highlighting of free or do you want me to do
something else?
Not neccessarily, just think about it, I don't really have a suggestion for
it.

**Comment by TheAssassin** [comment]
@TobiGr:

```
When you give our devs some snacks during work the will work faster and more efficient. As you know it is impossible to work with an empty stomach.
```

should be

```
When you give our devs some snacks during work, they will work faster and more efficient. As you know, it is impossible to work with an empty stomach.
```

Also, `an empty stomach` is not an English proverb, but interpreting by translating back to German, I'd use this wording:

> An empty bag cannot stand upright.

See e.g., https://idioms.thefreedictionary.com/an+empty+sack+cannot+stand+upright for an explanation.

**Comment by TobiGr** [comment]
@wb9688  Thanks. I didn't expected it to be a regex :)
@TheAssassin I'll change it.
