### ISSUE TITLE
Can not run website with jekyll

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/website#41]
When I try to run the website with `~ $ jekyll serve` I get this error:
```
/var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find sass-3.5.3 in any of the sources (Bundler::GemNotFound)
	from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
	from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
	from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
	from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
	from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
	from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
	from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
	from /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	from /var/lib/gems/2.3.0/gems/jekyll-3.6.2/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```
I run in on a current ubuntu installation (digitalocean), where only sass 3.4.21 is available.
@TheAssassin you said you use docker for this, how can I get your docer installation?
@TobiGr how did you setup the environment for development? On which distor are you running this?

**Comment by TobiGr** [comment]
>  Could not find sass-3.5.3 in any of the sources 

Please try to run `$ bundle install` in your directory. This should solve your problem. I'll add it to the readme.

**Comment by TobiGr** [comment]
Sorry, I didn't realized this line.

> I run in on a current ubuntu installation (digitalocean), where only sass 3.4.21 is available.

https://github.com/TeamNewPipe/website/blob/fd01c237fa2c2c5933e95923cc49ba30415a10e5/Gemfile.lock#L43

It shouldn't cause problems when you change this line.

**Comment by TheAssassin** [comment]
@theScrabi just get `docker-compose`, then run `docker-compose up --build -d`. You can reach the blog with a demo instance of isso on "http://127.0.0.1:8080". Just call docker-compose again to update your installation.

**Comment by theScrabi** [comment]
all right thanks :)
