### ISSUE TITLE
Add blog post for 34C3 video

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/website#43]
We need to eventually post the 34c3 video its almost 2 months now, and nothing happened yet. It's time this goes online otherwise all the work involved would have been for nothing ;)

**Comment by TheAssassin** [comment]
>  almost 2 months

Correct would be: "just over a month".

Working on it.

**Comment by TobiGr** [comment]
We should add the slides to the website.

**Comment by dompetpoker182** [comment]
very interesting article, thanks for the information
https://www.dynadot.com/community/blog/radix-choosing-domain-extension-guide-new-business.html
http://dompetpoker.net/
http://dompetcasino.com/
