### ISSUE TITLE
Menu inconsistency leading to wrong clicks

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#48]
On the main page, the menu is different than on other pages (the "Home" entry is missing, and it's aligned differently).

When browsing the page quickly, I often click on the wrong entry when switching between home page, blog and press entries.

I understand a "Home" entry isn't necessary on the home page, but think like this: Same goes for "Press" on the press page, and "Blog" on the blog page.

Now, one could consider removing the buttons for the current pages elswhere, too, but I am strongly opposed to this, as then, the menu is still inconsistent across the pages.

Instead, please try to make the menu contain all elements all the time, and be at the exactly same position on all pages.

**Comment by TobiGr** [comment]
Yes, I already noticed that.

> Instead, please try to make the menu contain all elements all the time, and be at the exactly same position on all pages.

I intended to fix this as soon as I am done with my exams, because it annoyed me too.

**Comment by TheAssassin** [comment]
Thanks. It's not urgent at all. I just wanted to have it in the bug tracker.

**Comment by TheAssassin** [comment]
Big thanks to you, @TobiGr. It works perfectly fine now. I'll deploy it asap.
