### ISSUE TITLE
Add page for donations

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/website#5]
As @ponypower [mentioned](https://github.com/TeamNewPipe/NewPipe/issues/277#issuecomment-216072533), we need a subpage for donations.
So we have to discuss, which services should be offered and then gather the required information for coding.

**Comment by theScrabi** [comment]
That is a good idea. We should also discus how to handle donations.

**Comment by ponypower** [comment]
Basically the people who wants to donate determine what services we need to offer. In other words we gotta identify the mostly used channels in the past and figure out what services will be popular in the future.

**Comment by TheAssassin** [comment]
During my life as a free software developer, I've seen and/or met a few options. All of them are some kind of crowdfunding methods.

**Proprietary, most popular, most annoying**

 - PayPal: proprietary payment system, charges fees for every transaction from recipients, they're quite awful especially for smaller amounts of money. Okayish platform, haven't tried the donation feature yet, but heard good things about it.
 - Patreon: Not as old as PayPal, but definitely nothing that was new to the market, charges a fee of 5% for every transaction, they're not as greedy as paypal but if there's any kind of fees during the transaction (like credit card), you have to pay for them too (e.g. 5% + credit card 4% = 9%). You're quite happy to see 0.90 for every dollar. Haven't used it myself, but [Red Eclipse](http://redeclipse.net)'s [main dev](https://patreon.com/qreeves) uses it.
 - Flattr: Another older system, been around for many years, also quite  popular among software developers. Never used it, a few projects called it a "good solution" a few years ago, also quite greedy (10% unless you're a charity).

**Open source, free, quite popular and anonymous**

 - Bitcoin: the oldest, most famous and most popular one. Doesn't charge ANY fees, is free for anyone to use, and anonymous (until you want real money for your bitcoins at least, donors will remain anonymous anyway). Easy to set up, easy to use.
 - other crypto currencies: mostly like Bitcoin, usually not worth supporting them as most people use Bitcoin anyway (Bitcoin's market share: >85%)

**Open, cheap, simple to use (at least for people in the same country as you)**

 - Put money in an envelope and send it to the dev: Quite simple approach, easy, anonymous (for the donor), and quite cheap for bigger transactions. Not very popular in software development, but some blogs (e.g. https://netzpolitik.org) have made some positive experiences with it.

Of course, there's many more alternatives for crowdfunding, but these are probably the most realizable ones.

I could imagine setting up a Bitcoin wallet and a PayPal account for this project, and adding two donation buttons to the index page.
There's no real need for a separate page, unless you want to write a few words about you being an African monarch that is in a bad situation and that you just need the money to be able to transfer that 2 million bucks and would share it with the donors after they've sent you their money.

**Comment by theScrabi** [comment]
@TheAssassin `During my life as a free software developer ...` like you are that old xD

**Comment by zoff99** [comment]
https://stripe.com

**Comment by TheAssassin** [comment]
Stripe has been designed for credit cards only at first, new payment methods like SEPA transactions have been added just recently. Fees are similar to PayPal. Never used it though, just read about someone integrate it into a Python web application, which didn't look too complicated.
https://stripe.com/de/pricing

**Comment by ponypower** [comment]
I have no idea how much we can expect for the project.
- I think the first goal should be covering the yearly costs, like running the website. Or is the current domain free of charges? How about www.newpipe.com? Is that too ambitious?
- When we go above the costs we don't have to immediatelly distribute it in pennies and such. We could just collect it till the end of the year and then see how much it is and what we can do with it. So **no rush in general**.
- The idea of aimed donation sounds interesting. Donators could choose the whole project in general, or parts of it, or even one particular developer. On the other hand some devs can be in the spotlight while other devs doing just as much in the background wouldn't get much attention. That would be unfair overall. I think we should keep the "right" for redistributing (about 50% of) the aimed donations, and have a clear statement about it when someone is about to do that.
- We could note how many hours we spent the given month on working. Also categories could be specified and we would distribute the donations accordingly. 

But first, we gotta get the site running :)

**Comment by TheAssassin** [comment]
`newpipe.com` is owned by one of those really annoying domain parking services. They want 2500 bucks for that domain? No way, that'd be a waste of money. We'd find another domain. But I think `newpipe.schabi.org` will do the job for now.

Speaking about yearly costs: There's some yearly costs for renting `schabi.org`, and of course for renting my server which is running most services at the moment (although I wouldn't want to charge the project for that as long as the resource usage for NewPipe is as low as at the moment).

I don't think that any money should go directly to developers but better cover all the other costs. I agree we should save the money until it is really needed. I could imagine running our own VPS for NewPipe for example, where we can run additional developer tools than [Sentry](https://support.schabi.org), e.g. the mailing list. Paying the developers directly probably won't increase their productivity.

**Comment by ponypower** [comment]
@TheAssassin I didn't know the site runs from your server free of charge. That's pretty nice of you!
> Paying the developers directly probably won't increase their productivity.

I think that's not the right approach. Devs voluntary spend their free time on the project. And donators do not pay, They donate. Donation is a meaningful form of appreciation and help. It's not about getting payed but feeling appreciated. It's more like a gesture I believe.

**Comment by TheAssassin** [comment]
> @TheAssassin I didn't know the site runs from your server free of charge. That's pretty nice of you!

Nevermind, there's plenty of resources left (CPU, RAM, traffic), NewPipe stuff don't use much resources.

> I think that's not the right approach. Devs voluntary spend their free time on the project. And donators do not pay, They donate. Donation is a meaningful form of appreciation and help. It's not about getting payed but feeling appreciated. It's more like a gesture I believe.

In my experience, people usually donate to fund new features that cost money. I haven't met anyone donate as a gesture, the donors usually want something new for their money (no, existing software doesn't count), which is why I called them payments instead of gestures. That's why I suggested to collect the money centrally and use it to pay for fees or other regular costs. Some projects also pay for software that their developers might want to use for example. They fund "things" and hand them to the devs instead of giving them the money itself.

And from a transparency point of view, that approach will be tricky, too. Most projects publish the donations they received, so we'd have to centrally manage them anyway to realize that.

**Comment by ponypower** [comment]
Fair enough. Now I'm curious what's the broader opinion on this here.

**Comment by wb9688** [comment]
What about something like [Bountysource](https://www.bountysource.com/)?

**Comment by theScrabi** [comment]
We talked about that, and I kind of liked it, but it also turned out that developing with that kind of thing has some disadvantages.
The concern would be that some people would write their bounty, get their reward, and than leave forever without maintaining what they did.

**Comment by ponypower** [comment]
about bounty&leave; I say worrying about maintenance is generally just the next step, first we just gotta get things done, thats how projects go forward

**Comment by theScrabi** [comment]
Ok I'll think about it :)

**Comment by theScrabi** [comment]
Ok I'd be good with that idea: https://github.com/TeamNewPipe/NewPipe/issues/534

**Comment by TobiGr** [comment]
Here are my ideas for the donation page:

- [desktop size](https://user-images.githubusercontent.com/17365767/28065317-53b034e0-6638-11e7-801a-665628f13bd2.png)
- [mobile size](https://user-images.githubusercontent.com/17365767/28065316-53aa9fbc-6638-11e7-8488-5923c3911b30.png)
- [BitCoin Popup](https://user-images.githubusercontent.com/17365767/28065318-53b198e4-6638-11e7-8354-d86bd30e00b7.png)

If you want, we can add more information about what we do with the donated money. I'm also not sure if we'll need the buttons to select the amount of money the people want to donate. ATM we can only use them for BitCoin donations. The idea behind the buttons is to get a user action which animates the user to make a donation.

**Comment by TheAssassin** [comment]
It's "Bitcoin". Also, it's " boost".

I'd write "One-time donation" instead of calling it normal. We might add regular donation features in the future, and they should be prioritized, as regular donations are better.

I'd further remove 1USD from the list. They're not really worth the effort. If someone wants to donate that amount nevertheless, they can use the custom amount features.

**Comment by TheAssassin** [comment]
You can also remove the gray area below the buttons.

I also don't like the huge red text in the bitcoin modal's lower area. Beware of saying thanks too often. The donors profit already because they can use NP free of charge. A single "thank you" will do.

Other than that, looks like a good start to me.

**Comment by bisam** [comment]
Just as a reminder, the website has this "Donation" button but it is not working. Perhaps you should mention that there currently is no official way to donate, so people don't have to look for this issue to find out :)

**Comment by TheAssassin** [comment]
@theScrabi, everyone's waiting for Bountysource. Can you provide an ETA for that?

**Comment by TobiGr** [comment]
If @theScrabi needs some time we could insert a modal with information about our Bitcoin address or use the button to link to the app's README page which also contains the Bitcoin address.

**Comment by theScrabi** [comment]
@TobiGr @TheAssassin @mauriciocolli @coffeemakr @BlenderViking  as it seams we have to wait a little until they enable us as team member (an employe of Bountysource has to unlock us).
You guys can claim to be a team member [here](https://www.bountysource.com/teams/newpipe).
