### ISSUE TITLE
Blog as rss fed

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/website#51]
I know we aren't using a CMS, but was it still possible to offet our blog as an rss feed?

**Comment by TobiGr** [comment]
Yes, I did test and it worked. Give me a week or so and I'll include everything needed.

**Comment by TheAssassin** [comment]
Thanks @TobiGr.

**Comment by theScrabi** [comment]
Awesome :)

**Comment by TobiGr** [comment]
@theScrabi Is that enough or do you need more information?
![newpipe - feed](https://user-images.githubusercontent.com/17365767/36857758-a7e36d72-1d79-11e8-9e06-20064d6f75b4.png)
```
<?xml version="1.0" encoding="utf-8"?> 
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"> 
<channel> 
<title>NewPipe Blog</title> 
<description>The latest news about NewPipe</description> 
<link href="{{ site.url }}/" rel="alternate" type="text/html" title="{{ site.title }}" /> 
{% for post in site.posts %}{% unless post.draft %} 
<item> 
<title>{{ post.title | xml_escape }}</title> 
<description>{{ post.content | xml_escape }}</description> 
<pubDate>{{ post.date | date_to_xmlschema }}</pubDate> 
<author><name>{{ post.author }}</name></author> 
<link href="{{ post.url | prepend: site.url }}" rel="alternate" type="text/html" title="{{ post.title }}" /> 
<guid isPermaLink="true">{{ post.url | prepend: site.url }}</guid> 
</item> 
{% endunless %}{% endfor %} 
</channel> 
</rss>
```

**Comment by TobiGr** [comment]
Btw we can also make a custom feed containing only the last post info or so. Just tell me what you need.

**Comment by theScrabi** [comment]
Thats cool :D Are the thumbnails part of the feed?

**Comment by TobiGr** [comment]
No, but I can figure something out to get them in.

**Comment by TobiGr** [comment]
We can use the `<enclosure>` tag to get media information into the feed. As a result, we have to provide more information in `images.yml` to get a valid feed.
Which URI should the feed have? https://newpipe.schabi.org/rss/feed.xml for thte whole feed and https://newpipe.schabi.org/rss/latest.xml for the latest blog entry? Or do we only need the first one? Give me that info and a PR should be there soon.

**Comment by theScrabi** [comment]
Yes sounds good :)

**Comment by TheAssassin** [comment]
I suggest `newpipe.schabi.org/feed/news.[rss|atom]`.
You probably noticed the `atom` part. I'd like to offer an Atom feed as well, if possible.
