### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#59]
```
Uncaught TypeError: Cannot read property 'split' of undefined
    at updateAllWithAPIData (web-api.js:44)
```

Just noticed this error after deploying the current state (merge of PR #58). I run Chromium Version 64.0.3282.167 on Ubuntu 16.04.

**Comment by TobiGr** [comment]
api.stats.changelog doesn't exist yet. That's the reason. And what FF says :) First time I saw that FF has better debugging than Chromium...

**Comment by TobiGr** [comment]
Fix in 066f2f055734c854bc34e0753e4b592ce27e1ddb

**Comment by TheAssassin** [comment]
I see. Can you please request this feature in the web-api repo? I don't remember an issue about this.

**Comment by TheAssassin** [comment]
```
Uncaught SyntaxError: Unexpected token }
```

You commented a bit too fast.

**Comment by TobiGr** [comment]
The comment should've started one line above 😫

**Comment by TheAssassin** [comment]
By the way, why are you using a synchronous request to query the API? I mean, you're using JQuery already anyway. You could simply use `$.get(...)` with a callback. Chromium shows warnings about it.

**Comment by TobiGr** [comment]
Yes that's right. I can changed it. The reason I didn't do it, is - AFAIK -  that `$(document).ready()` functions are triggered asynchronously.

**Comment by TheAssassin** [comment]
@TobiGr JavaScript code runs in a single thread. "Running asynchronously" doesn't mean it's run in another thread. The `$(document).ready()` callback is run in the same thread as well. Therefore, a synchronous request is always blocking this thread. If it's run asynchronously, the JavaScript interpreter will open the TCP port, send the request, and as soon as the JavaScript interpreter receives a response, it'll schedule the callback to be called next. There is definitely no parallelization. See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests.

**Comment by TobiGr** [comment]
I think we can close this as it is fixed.
