### ISSUE TITLE
Set comment hints to English

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/website#65]
Our entire website is written in English, just as the comments should be too. Therefore I'd suggest to remove the isso translations. This would also make it easier to modify our isso version. E.g I added an information about what Markdown features are supported - in English. And that's obviously not what I'd expect when the complete commenting system is explained in my language.
Besides that, we got Turkey and Portuguese comments too. We could try to avoid them by not providing other languages besides English.
@theScrabi @TheAssassin What's you opinion on that?

**Comment by TheAssassin** [comment]
@TobiGr I'm struggling with getting the Docker version of the latest isso play well with the main website.

Apparently we used the last release which was published like 2 years ago.

Other than that, I don't think we should remove the translations. I bet other systems like Disqus would show you everything in your language as well when logged in.

**Comment by theScrabi** [comment]
> We could try to avoid them by not providing other languages besides English.

I think it should be code of conduct of our blog to speak english. This way everyone can talk to everyone. Just like i wrote it in the CONTRIBUTING.md [here](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#issue-reportingfeature-requests)

**Comment by TheAssassin** [comment]
@theScrabi sure, I don't argue with that. My point is that it doesn't make sense to remove the translations, at least not to me. I think people are smart enough to see that the blog is written in English. And just because controls are in English, it doesn't mean people will write in English only.

**Comment by theScrabi** [comment]
Ah I get it, no I think the translations can remain, that would not make a difference xD

**Comment by TobiGr** [comment]
Ok. Then we'll keep the translations 👍
