### ISSUE TITLE
Buttons for sliders

### ISSUE THREAD

**Issue by rugk** [TeamNewPipe/website#68]
![grafik](https://user-images.githubusercontent.com/11966684/38776163-ebe3a4ec-4092-11e8-827f-c38ffa9e7fbc.png)

There should be buttons on the left/right I can use to click through the list.
Otherwise the small buttons are often hard to click.

**Comment by TobiGr** [comment]
The reason I disabled them is that they looked a little lost. I can imagine to display them when hovering the box. I'll need to take a closer look on what to do with smaller screens/mobiles.
