### ISSUE TITLE
Sliders should support swipe

### ISSUE THREAD

**Issue by rugk** [TeamNewPipe/website#70]
Follow-up of https://github.com/TeamNewPipe/website/issues/68#issuecomment-381389994

On mobile (or rather, all devices, because desktop/laptops also often have touch) you should support swiping through the sliders/quotes list

**Comment by TobiGr** [comment]
Fixed in 35ee06723a6e06cae35973d7116d21763197c65d and f3969af248c17acd9478f3a14187423f75a2fe40.

**Comment by TheAssassin** [comment]
Good idea, @rugk. Looking forward to testing it, @TobiGr. I'll deploy the changes immediately.

**Comment by rugk** [comment]
Great, it works!
