### ISSUE TITLE
Integrate current Git commit ID in footer

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#80]
I'd like to have the current Git commit ID somewhere on the page, ideally in the footer. This way, it's transparent to everyone what's been deployed. We could even make it a link back to the repo on GitHub.

**Comment by TobiGr** [comment]
Good idea. The guys over at F-Droid do the same. I guess [this merge request](https://gitlab.com/fdroid/fdroid-website/merge_requests/97) will help.

**Comment by TheAssassin** [comment]
Embedding the contents of `git rev-parse --short HEAD` should do the job.

**Comment by TobiGr** [comment]
I can't find a good position. Where do you want to place it? Next to the `Copyright © NewPipe` or somewhere else?

**Comment by TheAssassin** [comment]
@TobiGr copyright seems fine to me. The readthedocs.org Sphinx theme does that, too. Check out https://docs.appimage.org/.

**Comment by TheAssassin** [comment]
Thanks! Deploying in a minute.

**Comment by TobiGr** [comment]
These changes were stashed for quite a while :) I forgot to commit and push them 😄 
Unfortunately, I cannot get Docker to work with the latest changes properly. Using `COPY .git .git` ends in an issue telling me the file/directory does not exist. I used `rm` and `rmi` and the usual stuff to reset the environment completely, but the issue still exists. 
Do you think it might be a problem that the `.git` directory is a hidden dir?
