### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/website#99]
Right now, if we'd change a URL (e.g., by accident), we'd end up with an nginx-generated 404 page. That's not very user friendly, as a user couldn't even navigate to a non-404 page, or look for the right URL.

@TobiGr if you have some time, I would love to see a custom 404 page that employs our main page's design, including the top menu.

**Comment by TobiGr** [comment]
https://github.com/TeamNewPipe/website/blob/master/press/404.html
https://github.com/TeamNewPipe/website/blob/master/blog/404.html
They stopped working as I merged my blog repo into the normal website repository. Can you checkout https://jekyllrb.com/tutorials/custom-404-page/#hosting-on-nginx-server to get the nginx config right? 
Apart from that I'll look into a good design for a general 404 page.

**Comment by TheAssassin** [comment]
JFYI: the error pages have been set up for blog and press. See https://github.com/TeamNewPipe/website/commit/2af4a7e00cc5f718a5a552d3880f3421478bfdda.

**Comment by PotatoMasherGUI** [comment]
Here are the steps that can be taken to fix the issue of users getting an nginx-generated 404 page when a URL is changed on the NewPipe website:

    1. Identify the pages where this issue occurs: The first step is to identify the pages where this issue occurs. This can be done by testing the website thoroughly and checking for pages where changing the URL results in a 404 error.

    2. Implement a custom 404 page: Once the pages where the issue occurs have been identified, a custom 404 page can be implemented. This page should have a user-friendly message that informs the user that the page they are looking for does not exist, and should provide them with options to navigate to other pages on the website.

    3. Redirect the user to the custom 404 page: When a user enters an incorrect URL, instead of showing them the nginx-generated 404 page, they should be redirected to the custom 404 page. This can be done by configuring the web server to redirect all 404 errors to the custom 404 page.

    4. Implement a search function: To make it easier for users to find the page they are looking for, a search function can be implemented on the custom 404 page. This will allow users to search for the page they want, and will help them find it more quickly.

    5. Test the custom 404 page: Once the custom 404 page has been implemented, it should be thoroughly tested to ensure that it is working correctly. This includes testing it with various incorrect URLs to ensure that users are being redirected to the custom 404 page.

By following these steps, the issue of users getting an nginx-generated 404 page when a URL is changed on the NewPipe website can be fixed, and users will have a more user-friendly experience when navigating the website.
